---
title: "Two-Way Ancova"
author: "Carmen Garcia-Russell"
date: '2023-03-02'
output:
  html_document:
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

  After all data was collected, R-Studio was used to run a Two-Way Ancova test for the first two questions, and an independent t-test for the third question. The Two-Way Ancova test results were that was not a significant main effect on the years sentenced of the data that was selected, F(1, 1.4), p = 0.22 (see Figure 2). There was a significant main effect on the participants idea of how bad the crime was related to the years sentenced of the data that was selected, F(1, 22.4), p < 0.001. This second result doesn’t affect our hypothesis but does show that participants were consistent with their ideals on the crime and the time sentenced following it. There was no significant interaction effect between the Hispanic and Non-Hispanic populations F(1, 0.02), p = 0.89. When testing to see if participants saw a difference in skin hue a t-test was run and there was on average a significant difference on the perception between the dark-skinned mug shot (M=5.07, SE = 0.29), and the light-skinned mug shot (M= 3.84, SE = 0.29). This difference, 1.23, 95% CI[0.59, 0.6] was significant p = 0.004.