---
title: "Two-Way Ancova"
author: "Carmen Garcia-Russell"
date: '2023-03-02'
output:
  html_document:
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
There are many statisical tests, however I decided to run a two-way ancova. He ran the whole sample population as well as the hispanic populartion against the non-hispanic population. The covarient was how bad partcipants thought the crime was and the main variable was how many years Mr. Hernandez was sentenced to prision.


After all data was collected, R-Studio was used to run a Two-Way Ancova test for the first two questions, and an independent t-test for the third question. The Two-Way Ancova test results were that was not a significant main effect on the years sentenced of the data that was selected, F(1, 1.4), p = 0.22 (see Figure 2). There was a significant main effect on the participants idea of how bad the crime was related to the years sentenced of the data that was selected, F(1, 22.4), p < 0.001. This second result doesn’t affect our hypothesis but does show that participants were consistent with their ideals on the crime and the time sentenced following it. There was no significant interaction effect between the Hispanic and Non-Hispanic populations F(1, 0.02), p = 0.89.
